
jobs:

  admission:
    transformation:
      derive_date_fields:
        column_name: 'timestamp'
    cleansing:
      keep_most_recent_register_based_on_column:
        column_name: 'timestamp'
        identity_column_name: 'event_id' 
    input:
      type: json
      path: 'file://///transient/upstream_default'
    output: 
      type: parquet
      path: 'file://///raw/upstream_default'
      mode: overwrite
      partition_by: ['year', 'month', 'day']

  refining:
    depends_on: 
      - admission
    quality:
      uniqueness_based_on_columns: 
        columns:
          - 'event_id'
    input:
      type: parquet
      path: 'file://///raw/upstream_default'      
    output: 
      type: parquet
      path: 'file://///trusted/{dataset_name}'
      mode: overwrite
      partition_by: ['year', 'month', 'day']      

