
jobs:

  admission:
    incremental_strategy: 
      type: datetime
      column_name: 'date'
    cleansing:
      keep_most_recent_register_based_on_column:
        column_name: 'date'
        identity_column_name: 'id' 
    input:
      type: json
      path: 'file://///transient/upstream_default'
    output: 
      type: parquet
      path: 'file://///raw/upstream_default'
      partition_by: ['year', 'month', 'day']

  refining:
    depends_on: 
      - admission
    incremental_strategy: 
      type: datetime
      column_name: 'date'
    quality:
      uniqueness_based_on_columns: 'id'
    input:
      type: parquet
      path: 'file://///raw/upstream_default'      
    output: 
      type: parquet
      path: 'file://///trusted/{dataset_name}'
      partition_by: ['year', 'month', 'day']      

